services:
  - type: web
    name: conxian-labs-site
    env: node
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    pullRequestPreviewsEnabled: yes
    autoDeploy: yes

